SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM rentals;
DELETE FROM movies;
DELETE FROM users;

ALTER TABLE rentals AUTO_INCREMENT = 1;
ALTER TABLE movies  AUTO_INCREMENT = 1;
ALTER TABLE users   AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;
